remote_theme: just-the-docs/just-the-docs
title: Books
description: Educational purposes only
nav_external_links:
  - title: Educated
    url: /Educated.pdf
    parent: 10th
    nav_order: 2
    hide_icon: true